server:
  port: 80
  servlet:
    encoding:
      charset: UTF-8
      force: true
spring:
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
logging:
  level:
    root: info


app:
  dir:
    imgdir: file:///c:/springsm/imgs/
    logdir: file:///c:/springsm/logs/ #저장할때는 앞에 file이 붙어야함
    readlogdir: c:/springsm/logs/ # 이 위치에서 log를 가져온다 이거임